version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80 
    networks:
      - glamai_network
    restart: always

networks:
  glamai_network:
    driver: bridge
